### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by TheRaddish1313** [atrexus/unluau#29]
I read everything and how to execute the commands everytime i typed something for example, the commands everytime it says failed even though nothing has even happened yet, please help im very confused.

**Comment by atrexus** [comment]
There are no commands. You need to launch Unluau from the command line.

**Comment by TheRaddish1313** [comment]
I'm still confused I did.

**Comment by TheRaddish1313** [comment]
it keeps saying "decompile error"

**Comment by atrexus** [comment]
> it keeps saying "decompile error"

I don't understand. Please explain to me how you are using Unluau and show me the output it is giving you.

**Comment by TheRaddish1313** [comment]
I opent he win-64 folder and type the script i want it to decompile everytime i do it, it says decompile error or failed and the command thing closes.

**Comment by atrexus** [comment]
Please read up on "command line arguments" because I don't think you understand what they are or how to use them.
