### ISSUE TITLE
"..." instead of ".."

### ISSUE THREAD

**Issue by alternativebyte** [atrexus/unluau#31]
Hello! So this is a quick fix! For some weird reason, it says "..." instead of "." I'm pretty sure the culprit is this: "\Unluau\Lifter\Expressions\Vararg.cs" On line 16, it says "output. Write "..." when it should be "output. Write("..");" This is just weird, and please note that I don't know a lot about scripting, so if this is for something else, please tell me.

**Comment by atrexus** [comment]
This is for variable number arguments: https://www.lua.org/pil/5.2.html. It is not a bug,
