### ISSUE TITLE
idk v2

### ISSUE THREAD

**Issue by karl-police** [atrexus/unluau#35]
![image](https://github.com/atrexus/unluau/assets/12023782/667f1f75-bcbc-4d78-b627-f8ffd1876b35)

Just like... whyyyy 😐 

Somehow this thing goes ``-1`` or lower

**Comment by atrexus** [comment]
This looks like the source code of the `2.0.0-beta` version. Could you provide the file with the bytecode that provided this error? I have been taking a break from this project, so sorry for the late responses.

**Comment by karl-police** [comment]
> This looks like the source code of the `2.0.0-beta` version. Could you provide the file with the bytecode that provided this error? I have been taking a break from this project, so sorry for the late responses.

should be this one https://github.com/MaximumADHD/Roblox-Client-Tracker/blob/roblox/BuiltInPlugins/AnimationClipEditor/Src/Components/AnimationClipEditorPlugin.luac


I did try to figure out by myself, but this is an entire file format parsing alike thing, it's very complicated to debug

**Comment by karl-police** [comment]
Mine doesn't error at this, nor does the old version.


If I remember right, it errors at Import Constant of a Proto. I had the splendid idea to put Math.Abs or (uint) on it. That worked but then there where more errors. Not sure. I am not entirely sure what ReadSize does or how much it reads. I wonder if there's an issue in offset or something.

&nbsp;

If you look at my repo, I started doing it with C++, also in C# but then I continued it on C++. But one of my test files, managed to mess it up...

I believe it was because I am missing out on offsetting something while reading the chunk, but I couldn't really figure out what, and that was so frustrating. Luau's repository might hold the answer for mine, but I couldn't figure out.

A thing I figured out was that I had to manually offset while reading the Strings Chunk, while on Luau they just offset the Length. And I believe that I am missing that sort of part somewhere at the Protos.

**Comment by karl-police** [comment]
> This looks like the source code of the `2.0.0-beta` version. Could you provide the file with the bytecode that provided this error? I have been taking a break from this project, so sorry for the late responses.

Yours also errors with this one. https://github.com/karl-police/luau-pseudo-code/blob/6d1d2b11289fe7070cb23b9f1f64c0057841d0f4/src/tests/abc.lua.luac

Same as mine, maybe at a different location, not sure.

I think the Source Code for it was

```lua
local test = "wat"

function modify()
    test = "modified"
end

modify()
```

**Comment by karl-police** [comment]
> This looks like the source code of the `2.0.0-beta` version. Could you provide the file with the bytecode that provided this error? I have been taking a break from this project, so sorry for the late responses.

![image](https://github.com/atrexus/unluau/assets/12023782/8c432d2d-6aa7-424a-a972-daeb5580ac3f)


The thing with the abc.lua.luac is a Luau Bug. Not even Analyze can analyze it.

**Comment by karl-police** [comment]
I think GETIMPORT is not designed to be a positive value that easily. Maybe you need to remove or re-design ImportConstant completely, because not sure.

**Comment by atrexus** [comment]
Just so you know, `v2.0.0-beta` is still under development and has bugs that I haven't been able to get to yet. It doesn't generate Lua code, but generates code in an intermediate language (IL). I still need to write the AST builder as well as stress test the code. For now, please use any of the `alpha` versions, they should provide better support.

**Comment by karl-police** [comment]
> Just so you know, `v2.0.0-beta` is still under development and has bugs that I haven't been able to get to yet. It doesn't generate Lua code, but generates code in an intermediate language (IL). I still need to write the AST builder as well as stress test the code. For now, please use any of the `alpha` versions, they should provide better support.

I made pull requests though

I was trying to fix it

&nbsp;

Idk why you'd want to make an AST generator, if it doesn't create Pseudo Code it's pointless.

**Comment by atrexus** [comment]
> > Just so you know, `v2.0.0-beta` is still under development and has bugs that I haven't been able to get to yet. It doesn't generate Lua code, but generates code in an intermediate language (IL). I still need to write the AST builder as well as stress test the code. For now, please use any of the `alpha` versions, they should provide better support.
> 
> I made pull requests though
> 
> I was trying to fix it
> 
>  
> 
> Idk why you'd want to make an AST generator, if it doesn't aid in the creation of Pseudo Code, then it's pointless.

Building an AST is incredibly important. With it, we can generate all sorts of "pseudo codes". Read more [here](https://en.wikipedia.org/wiki/Abstract_syntax_tree).

**Comment by atrexus** [comment]
> > This looks like the source code of the `2.0.0-beta` version. Could you provide the file with the bytecode that provided this error? I have been taking a break from this project, so sorry for the late responses.
> 
> Yours also errors with this one. https://github.com/karl-police/luau-pseudo-code/blob/6d1d2b11289fe7070cb23b9f1f64c0057841d0f4/src/tests/abc.lua.luac
> 
> Same as mine, maybe at a different location, not sure.
> 
> I think the Source Code for it was
> 
> ```lua
> local test = "wat"
> 
> function modify()
>     test = "modified"
> end
> 
> modify()
> ```
> 
> Well, in comparison to mine, you seem to have managed to make it past the closure table. I didn't but yours errors out at the same location as mine does, Constant Type 65 not existing. I don't know if this is a failure by Luau V5 or something else.

The latest version has not implemented closures yet. Only works for Lua programs that don't define functions. I will add this soon.

**Comment by atrexus** [comment]
I'm pretty sure that there aren't any problems with registers in v2. I would love to chat on Discord, my username is the same as my github: `atrexuss`.
