### ISSUE TITLE
Bytecode version mismatch

### ISSUE THREAD

**Issue by wal-ly** [atrexus/unluau#42]
Apparently support for version 4 was added in alpha-0.0.7, but doesn't seem to be the case for 1.0.9, not using v2 cause does not work on my machine™

![image](https://github.com/atrexus/unluau/assets/100832774/653bf5f5-cb2e-4aa1-9d44-3a26fd3f855b)

wasnt able to decompile/disasm anything

**Comment by atrexus** [comment]
This is because the bytecode you are trying to decompile is probably using Luau 5, which is not supported.

**Comment by wal-ly** [comment]
> This is because the bytecode you are trying to decompile is probably using Luau 5, which is not supported.

add support would be appreciated :)
