### ISSUE TITLE
unhandled operation code (130)

### ISSUE THREAD

**Issue by rekitrelt** [atrexus/unluau#47]
[bytecode.txt](https://github.com/atrexus/unluau/files/14861541/bytecode.txt)
even adding the person you forked off of's changes still get this error

**Comment by iivillian** [comment]
This bytecode has encoded opcodes, you must pass the command line argument for client to handle this.

Unluau.CLI.exe bytecode.txt --encoding=1

`-- Unluau v1.0.9-alpha guid: 39b2efa1-1b4f-46c5-8b5d-700bceb76b63
game:GetService("UserInputService").InputBegan:connect(function(arg1, arg2)
   if arg2 then
      return
   end
   local var0 = Enum.UserInputType.Keyboard
   if arg1.UserInputType == Enum.UserInputType.Keyboard then
      local var10 = Enum.KeyCode.F
      if arg1.KeyCode == Enum.UserInputType.Keyboard then
         game.ReplicatedStorage.Fart:FireServer()
         return
      end
      local var1 = Enum.KeyCode.G
      if arg1.KeyCode == Enum.UserInputType.Keyboard then
         game.ReplicatedStorage.Dab:FireServer()
      end
   end
end)`
