### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by rekitrelt** [atrexus/unluau#49]
Unluau.DecompilerException: unexpected constant passed to 'ConstantToExpression'
at Unluau.Lifter.ConstantToExpression(Constant constant) in C:\Users\rekitrelt\source\repos\unluau\src\Unluau\Lifter\Lifter.cs:line 810

**Comment by rekitrelt** [comment]
[script.txt](https://github.com/atrexus/unluau/files/14878819/script.txt)

**Comment by ChloeDoesThings** [comment]
What version of unluau did you use, one from releases?

**Comment by rekitrelt** [comment]
im using the latest version from releases with the update for bytecode version 5 from [MaximumADHD's](https://github.com/MaximumADHD/unluau) fork

**Comment by ChloeDoesThings** [comment]
> im using the latest version from releases with the update for bytecode version 5 from [MaximumADHD's](https://github.com/MaximumADHD/unluau) fork

Oh, maybe building the source for this will work since they just updated it with the latest opcodes and stuff for version 5 on here.

**Comment by ChloeDoesThings** [comment]
> > im using the latest version from releases with the update for bytecode version 5 from [MaximumADHD's](https://github.com/MaximumADHD/unluau) fork
> 
> Oh, maybe building the source for this will work since they just updated it with the latest opcodes and stuff for version 5 on here.

If you need me to build it for you lmk

**Comment by rekitrelt** [comment]
I just built it, now I get unhandled operation code (240)

**Comment by ChloeDoesThings** [comment]
idrk what to say other than make sure you're using the client encoding option for the cli

**Comment by rekitrelt** [comment]
oh right im dumb;
Unexpected error; please report here: https://github.com/atrexus/unluau/issues
System.NullReferenceException: Object reference not set to an instance of an object.
