### ISSUE TITLE
no support for newer bytecode versions?

### ISSUE THREAD

**Issue by SilvazWasTaken** [atrexus/unluau#61]
will there ever be an update to have bytecode 5 and 6

**Comment by atrexus** [comment]
Yes. I am currently working on [v2](https://github.com/atrexus/unluau/tree/v2.0.0-beta) which already lifts the latest bytecode versions. The current branch (any alpha editions) won't be updated until v2 is finished. 

If you want to add support yourself, feel free. Send a pull request and I'll review it.
